name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: docker://alpine
    - run: |
        echo Add other actions to build,
        echo test, and deploy your project.
